admin:
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }

# Identifies this envoy instance. Boilerplate, irrelevant to the example.
node:
  cluster: envoy-cluster
  id: envoy-node-1

# The listener is the entrypoint for the Envoy proxy.
static_resources:
  listeners:
  - name: listener_0
    address:
      # Listen on port 10000. This port is mapped to the host machine.
      # In the service mesh, traffic interception makes this port match the application port.
      # To simplify the example, there is no traffic interception here, and therefore the
      # Envoy proxy listens on port 10000 and forwards traffic to the Cassandra node on port 9042.
      socket_address: { address: 0.0.0.0, port_value: 10000 } 
    filter_chains:
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: tcp
          # Forward any TCP connections that authenticate via mTLS to the Cassandra node.
          cluster: cassandra-1
          upstream_connect_mode: ON_DOWNSTREAM_DATA
          max_early_data_bytes: 8192
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_certificate_sds_secret_configs:
            # The SPIFFE ID of the Cassandra cluster.
            - name: "spiffe://demo.trust.geico/cassandra-node"
              sds_config:
                resource_api_version: V3
                api_config_source:
                  api_type: GRPC
                  transport_api_version: V3
                  grpc_services:
                    envoy_grpc:
                      cluster_name: spire_agent
            combined_validation_context:
              # validate the SPIFFE ID of incoming clients (optionally)
              default_validation_context:
                match_typed_subject_alt_names:
                - san_type: URI
                  matcher:
                    # The SPIFFE ID of the client application. The client
                    # must present a certificate with this SPIFFE ID in the URI SAN list.
                    exact: "spiffe://demo.trust.geico/app"
              # obtain the trust bundle from SDS
              validation_context_sds_secret_config:
                # The trust domain for the SPIFFE ID of the client application.
                # Envoy will handle retrieving the trust bundle from the SPIRE agent.
                name: "spiffe://demo.trust.geico"
                sds_config:
                  resource_api_version: V3
                  api_config_source:
                    api_type: GRPC
                    transport_api_version: V3
                    grpc_services:
                      envoy_grpc:
                        cluster_name: spire_agent
            tls_params:
              ecdh_curves:
                - X25519:P-256:P-521:P-384
  clusters:
  # The pipe address for the SPIRE agent socket.
  - name: spire_agent
    connect_timeout: 0.25s
    http2_protocol_options: {}
    load_assignment:	
      cluster_name: spire_agent
      endpoints:	
      - lb_endpoints:	
        - endpoint:	
            address:	
              pipe:	
                path: /tmp/spire-agent/public/api.sock # the mounted volume path
  # The Cassandra container.
  - name: cassandra-1
    dns_refresh_rate: 180s
    connect_timeout: 0.25s
    type: STRICT_DNS # Resolve the Cassandra node IP via DNS, thanks to the docker bridge network. 
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: some_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: cassandra-1
                port_value: 9042